repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.7'
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|cxx|h)$

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        files: \.py$
